baseurl = "/"
title = "VCDB"
languageCode = "en-us"
theme = "terminal"
paginate = 50


[params]
    showFullContent = false
    summary = true

    # dir name of your blog content (default is `content/posts`)
    contentTypeName = "vcdb"
    # ["orange", "blue", "red", "green", "pink"]
    themeColor = "blue"
    # if you set this to 0, only submenu trigger will be visible
    showMenuItems = 5
    # set theme to full screen width
    fullWidthTheme = false
    # center theme with default width
    centerTheme = true
    # set a custom favicon (default is a `themeColor` square)
    # favicon = "favicon.ico"

    logo.logoText = "VCDB"
    logo.logoHomeLink = "/"

[menu]
[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
[[menu.main]]
    identifier = "vcdb"
    name = "All Challenges"
    url = "/vcdb"
    weight = 20
[[menu.main]]
    identifier = "contribution"
    name = "Contribution"
    url = "/contribution"
    weight = 30
[[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "/rss/"
    weight = 40
[[menu.main]]
    identifier = "credit"
    name = "Credit"
    url = "/credit/"
    weight = 50

